### PR TITLE
Fix metrics deletion

### PR DESCRIPTION
**Pull request by amityahav**
Hey there, we've integrated this service the company im working in. and we've noticed that once head stats cease to contain some record the service should delete the exported metric from its registry but it doesnt. this is due the misplace of the infinite for-loop which does all the init steps ,that should happen once, multiple times causing the `trackedLabels` field to be override each step hence loosing the trackedLabels from previous iterations.

i placed the for loop in its right place and tested it and it fixes the issue

### CODE REVIEW

**Comment by RichardoC** [comment]
Minor comment, mind undoing the ordering change to the third party deps? We try to have builtins, then third party imports rather than putting them all together.
Beyond that, I'll get someone to do an in depth review!

**Comment by harryfallows** [comment]
Hey, thanks for submitting a PR! I presume you are statically defining the endpoints and not using service discovery, right? I think the for loop currently works fine for service discovery because [there is a check to see if the prometheus instance already exists in the map so it doesn't get overwritten](https://github.com/thought-machine/prometheus-cardinality-exporter/blob/master/main.go#L130). We would want to keep the service discovery in the for loop, because we'd want to dynamically discover them without restarting the service. You're right about the non-service-discovery path not being in the for loop though, because the flags can't change without restarting the service, so I am happy for you to move that. Would you mind updating the PR to put the service discovery bit back into the for loop please? Other than that I think I am happy with this PR. Thanks!

**Comment by peterebden** [comment]
> Minor comment, mind undoing the ordering change to the third party deps? We try to have builtins, then third party imports rather than putting them all together.

I'll look at sending a PR adding a linter for this.

**Comment by amityahav** [comment]
did what you asked, let me know if thats ok

**Review by harryfallows — APPROVED** [review]
Hey, this looks good - I've deployed it to an internal environment and it seems to be working fine. Thanks for the contribution!

**Pull request merged**
